[package]
name = "womir-guest-io"
version = "0.0.1"
edition = "2021"

[dependencies]
serde = { version = "1.0", default-features = false }
postcard = { version = "1.1", default-features = false, features = ["alloc"] }
